import * as fs from 'fs';
import * as path from 'path';
import { loadEnvConfig } from '@next/env';

loadEnvConfig(process.cwd());

const DATABASE_TYPE = process.env.DATABASE_PROVIDER;
const BASE_SCHEMA_PATH = path.join(__dirname, '../prisma/base.schema.prisma');
const OUTPUT_SCHEMA_PATH = path.join(__dirname, '../prisma/schema.prisma');

const DB_CONFIGS = {
  sqlserver: {
    provider: 'sqlserver',
    urlEnv: 'DATABASE_URL_SQLSERVER',
  },
  postgresql: {
    provider: 'postgresql',
    urlEnv: 'DATABASE_URL_POSTGRESQL',
  },
} as const;

const generateSchema = () => {
  try {
    // Verify variables
    if (!DATABASE_TYPE || !DB_CONFIGS[DATABASE_TYPE as keyof typeof DB_CONFIGS]) {
      throw new Error(`Invalid or missing DATABASE_PROVIDER: "${DATABASE_TYPE}"`);
    }

    // Remove any existing schema.prisma files
    if (fs.existsSync(OUTPUT_SCHEMA_PATH)) {
      fs.rmSync(OUTPUT_SCHEMA_PATH, { force: true });
      console.log(`- Removed existing schema at ${OUTPUT_SCHEMA_PATH}`);
    }

    const config = DB_CONFIGS[DATABASE_TYPE as keyof typeof DB_CONFIGS];
    let schemaContent = fs.readFileSync(BASE_SCHEMA_PATH, 'utf-8');

    if (!config) {
      throw new Error(`Unsupported provider: ${DATABASE_TYPE}`);
    }

    const header = [
      '// !!! DO NOT EDIT THIS FILE DIRECTLY !!!',
      '// This file is auto-generated by scripts/build-schema.ts',
      `// Source: base.schema.prisma | Provider: ${DATABASE_TYPE}`,
      '',
      'datasource db {',
      `  provider = "${config.provider}"`,
      `  url      = env("${config.urlEnv}")`,
      '}',
      '',
      'generator client {',
      '  provider      = "prisma-client-js"',
      '  binaryTargets = ["native", "windows", "linux-musl-openssl-3.0.x"]',
      '}',
      '\n',
    ].join('\n');

    // Transform Schema based on DATABASE_TYPE
    if (DATABASE_TYPE !== 'sqlserver') {
      console.log('--- Non-SQLServer DB detected. Stripping @db attributes. ---');
      // Matches @db. followed by anything until a space or end of line
      // e.g., @db.NVarChar(255), @db.VarChar(Max), @db.NVarChar(4000)
      schemaContent = schemaContent.replace(/@db\.[a-zA-Z0-9_]+(\([^)]*\))?/g, '');
    } else {
      console.log('--- SQLServer DB detected. Preserving schema attributes. ---');
    }

    // Write New File
    const finalSchema = header + schemaContent;
    fs.writeFileSync(OUTPUT_SCHEMA_PATH, finalSchema);

    console.log(`Successfully generated: ${OUTPUT_SCHEMA_PATH}`);
  } catch (error) {
    console.error('Error generating Prisma schema:', error);
    process.exit(1);
  }
};

generateSchema();
